services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3001:3001"
    networks:
      - my-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    env_file:
      - .env
    command: npm run start:dev
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - my-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    working_dir: /app
    command: npm run dev

  db:
    image: postgres:latest
    container_name: ${DB_HOST}
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - my-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  my-network:
    driver: bridge
